### ISSUE TITLE
ZonedTime does not have the obvious instances

### ISSUE THREAD

**Issue by kqr** [nilcons/lens-datetime#2]
Is there any specific reason `ZonedTime` does not have a few instances to make it convenient to work with? For example, I had to define

    zonedAsLocal =
        lens zonedTimeToLocalTime (\s b -> s { zonedTimeToLocalTime = b })

    instance FlexibleDateTime ZonedTime where
        flexDT = zonedAsLocal.flexDT

    instance Timeable ZonedTime where
        time f (ZonedTime lt tz) = fmap (\lt2 -> ZonedTime lt2 tz) (time f lt)

to be able to do

    getZonedTime <&> time .~ midnight <&> hours +~ 1

Is this intentional because of some complication I'm not thinking of, or is it just that nobody has come around to write the instances yet?

**Comment by klao** [comment]
Thanks a lot for your comment, and sorry it took so long!

**Comment by kqr** [comment]
No problem. Thanks for making an awesome library!
