### ISSUE TITLE
Add library to stackage

### ISSUE THREAD

**Issue by dredozubov** [nilcons/lens-datetime#4]
Love the library, can you add it to stackage please?

**Comment by klao** [comment]
Sure, will try to do it asap! Thanks!

**Comment by klao** [comment]
I've sent a pull request for this.

https://github.com/fpco/stackage/pull/1397

**Comment by klao** [comment]
It's in! Should appear in the next nightly.

**Comment by dredozubov** [comment]
Great, thank you!
